[workspace]
members = [
    "src/common",
    "src/storage",
    "src/logical_expr",
    "src/logical_plan",
    "src/physical_expr",
    "src/physical_plan",
    "src/pgrepr",
    "src/pgwire",
    "src/fp",
]