[workspace]
members = [
    "src/common",
    "src/catalog",
    "src/storage",
    "src/kv",
    "src/sql",
    "src/pgrepr",
    "src/pgwire",
    "src/fp",
    "src/session",
    "src/test_util",
    "clients",
]