edition = "2021"
#imports_granularity = "Crate"
#group_imports = "StdExternalCrate"
#reorder_imports = true
#format_strings = true
#max_width = 100
#wrap_comments = true
#comment_width = 60
#fn_call_width = 60
#format_code_in_doc_comments = true



reorder_imports = true
format_strings = true
wrap_comments = true
unstable_features = true
max_width = 100
comment_width = 60
fn_call_width = 60