edition = "2021"
imports_granularity = "Crate"
group_imports = "StdExternalCrate"
reorder_imports = true
format_strings = true
wrap_comments = true
max_width = 100
comment_width = 60
fn_call_width = 60
format_code_in_doc_comments = true
normalize_comments = true